
DEFAULT = {}
DEFAULT["process"] = '1' ##set 1 to pre-process the data
DEFAULT["reconstruct"] = '1' ##set 1 to perform the reconstruction
DEFAULT["removeOutliers"] = '0' ##set 1 to remove outlier diffraction patterns
DEFAULT["lowPassFilter"] = '1' ##set 1 to low pass filter the data
DEFAULT["file_prefix"] = '' ##prefix used in the the file names before auto-increment
DEFAULT["dataPath"] = '' ##path to the auto-incremented directory tree
DEFAULT["dataFile"] = '' ##CXI file to use if not using auto-incremented tree
DEFAULT["saveFile"] = '0'
DEFAULT["speFile"] = '' ##SPE file to use if not using auto-incremented tree
DEFAULT["scanDate"] = '' ##scan date
DEFAULT["scanNumber"] = '' ##scan number
DEFAULT["scanID"] = '' ##scan ID
DEFAULT["scanDir"] = ''
DEFAULT["fileName"] = ''
DEFAULT["outputFilename"] = ''
DEFAULT["bgScanDate"] = ''
DEFAULT["bgScanNumber"] = ''
DEFAULT["bgScanID"] = ''
DEFAULT["bin"] = '1' ##number of datasets to average at each point
DEFAULT["interferometer"] = '1' ##set to 1 to use interferometer positions
DEFAULT["xaxis"] = 'b' ##file code for x axis interferometer data
DEFAULT["yaxis"] = 'c' ##file code for y axis interferometer data
DEFAULT["xaxisNo"] = '0' ##file code for x axis interferometer data
DEFAULT["yaxisNo"] = '0' ##file code for y axis interferometer data
DEFAULT["pixnm"] = '' ##requested pixel size in nm
DEFAULT["sh_sample_y"] = '' ##final resampled grid size
DEFAULT["sh_sample_x"] = '' ##final resampled grid size
DEFAULT["filter_width"] = '100' ##pixel width of the autocorrelation filter
DEFAULT['probeThreshold'] = '0.01' ##threshold to use for calculating probe from STXM brightfield
DEFAULT["ssx"] = '' ##step size in the x dimension in nm
DEFAULT["ssy"] = '' ##step size in the y dimension in nm
DEFAULT["ssn"] = '14' #number of pixels per scan step
DEFAULT["xpts"] = '' ##number of scan points in the x dimension
DEFAULT["ypts"] = '' ##number of scan points in the y dimension
DEFAULT["zd"] = '90' ##zone plate diameter in microns
DEFAULT["dr"] = '250' ##zone plate outer zone width
DEFAULT["e"] = '750' ##x-ray energy
DEFAULT["ccdp"] = '20' ##ccd pixel size in microns
DEFAULT["ccdz"] = '79.55' ##ccd distance from sample in mm
DEFAULT["nexp"] = '1' ##number of exposure times per point
DEFAULT["nl"] = '10' ##final lower threshold on the data
DEFAULT["xcenter"] = '' ##center x pixel in the raw data
DEFAULT["ycenter"] = '' ##center y pixel in the raw data
DEFAULT["t_long"] = '0' ##long exposure time
DEFAULT["t_short"] = '0' ##short exposure time
DEFAULT["s_threshold"] = '5000' ##upper threshold on saturated pixels
DEFAULT["nProcesses"] = '48' ##number of pre-processing processes to launch
DEFAULT["bl"] = 'ns' ##beamline tag                    p = Param()
DEFAULT["cxi"] = '1' ##set 1 to output to CXI file
DEFAULT["gpu"] = '0' ##set 1 to use the GPU
DEFAULT["nIterations"] = '100' ##number of iterations
DEFAULT["probeMask"] = '1' ##set 1 to use a fourier mask on the probe
DEFAULT["algorithm"] = 'raar' ##algorithm tag
DEFAULT["pR"] = '1' ##set 1 to use probe retrieval
DEFAULT["bR"] = '1' ##set 1 to use background retrieval
DEFAULT["useStxm"] = '0' ##set 1 to start from the STXM image
DEFAULT["version"] = '' ##set 2
DEFAULT['bg_filename'] = '' ##SPE file with background data if not using auto-increment
DEFAULT['zpw'] = '' ##width of the STXM brightfield annulus in pixel units in Fourier space
DEFAULT['short_filename'] = '0' ##SPE file with short exposures if recorded separately
DEFAULT['fCCD']='1' ##set 1 if using the fast CCD
DEFAULT['Year'] = ''
DEFAULT['Month'] = ''
DEFAULT['Day'] = ''
DEFAULT['Scientist'] = ''
DEFAULT['Sample'] = ''
DEFAULT['Comment1'] = ''
DEFAULT['Comment2'] = ''
DEFAULT['Id'] = ''
DEFAULT['beamstop'] = '5' ##thickness: 5,10,20
DEFAULT['processGPU'] = '0' ##set 1 to pre-process on the GPU
DEFAULT['fv'] = '0' ##set 1 to flip data vertically
DEFAULT['fh'] = '0' ##set 1 to flip data horizontally
DEFAULT['transpose'] = '0' ##set 1 to transpose the data
DEFAULT['sim'] = '0' ##set 1 if this is a simulation
DEFAULT['usePrevious'] = '0' ##set 1 to start from a previous reconstruction
DEFAULT['removePhasePlane'] = '1'
DEFAULT['beta'] = '0.6' #RAAR paramter: 0.5-1.0
DEFAULT["eta"] = '0.6' ##eta for background retrieval
DEFAULT['illuminationPeriod'] = '2' #Refine illumination every few iterations
DEFAULT['backgroundPeriod'] = '5'
DEFAULT['relaxedFourier'] = '0' #Relaxed Fourier Modulus constraints
DEFAULT['illuminationIntensities'] = '0' #Enforce illumination Fourier intensities
DEFAULT['illuminationMask'] = '1' #Enfornce mask on illumination intensities
DEFAULT['sh_crop'] = '600' #sub-matrix to use of the full fCCD RAW data
DEFAULT['paramFileName'] = '0'
DEFAULT['debug'] = '0'
DEFAULT['fCCD_version'] = '1' #1 for old and 2 for new
DEFAULT['loopSize'] = '10'
DEFAULT['nBlocks'] = '4'
DEFAULT['nGPU'] = '4'
DEFAULT['nCPU'] = '17'
DEFAULT['useCluster'] = '0'
DEFAULT['low_pass'] = '0' #switch to low pass the image because of strong scattering
DEFAULT['prtf'] = '0'
DEFAULT['beamStopTransmission'] = '0.015'
DEFAULT['itnGlobal'] = '0'
DEFAULT['logFile'] = 'ptychoLog.txt'
DEFAULT['finalError'] = '0'




